### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by tarabernal**
Added Lock Pick World under Vendors

### CODE REVIEW

**Comment by meitar** [comment]
This is an [advertisement](https://web.archive.org/web/20180725173245/https://www.prweb.com/releases/2017/07/prweb14512942.htm), not a contribution.

**Comment by tarabernal** [comment]
Hello,

If there's a fee for this, then I'd be willing to pay for it


*Tara Bernal*
www.lockpickworld.com

**Comment by meitar** [comment]
> Hello,
> 
> If there's a fee for this, then I'd be willing to pay for it
> 
> \*Tara Bernal*
> www.lockpickworld.com

[That's not how it works.](https://knowyourmeme.com/memes/thats-not-how-it-works-you-little-shit)

**Comment by tarabernal** [comment]
Hi,

Well sorry to hear that. I asked politely. You could have at least said it
in a nice manner.

Thank you and may God Bless you.





[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
07/26/18,
11:12:33 AM

*Tara Bernal*
www.lockpickworld.com

**Comment by meitar** [comment]
Twelve days later and you're still thinking about this? Gee, I must have touched a nerve. I'm also glad to see that LockPickWorld employs such professional individuals. :) Best wishes to you in your future business endeavors.

I'll just put [this link](https://web.archive.org/web/20180807035543/https://github.com/meitar/awesome-lockpicking/pull/3#issuecomment-410920648) here.

**Pull request closed without merging**
